/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import javax.swing.JOptionPane;
/**
 *
 * @author LAB_07
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPricipal
     */
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        itemEstado = new javax.swing.JMenuItem();
        itemCidade = new javax.swing.JMenuItem();
        itemCliente = new javax.swing.JMenuItem();
        itemProduto = new javax.swing.JMenuItem();
        itemFormaPagamento = new javax.swing.JMenuItem();
        menuMovimentacao = new javax.swing.JMenu();
        itemVenda = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        itemClienteCadastrosCidades = new javax.swing.JMenuItem();
        itemVendasRealizadasPeriodo = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();
        Equipe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Comercial - Business 1.0");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cafe.jpg"))); // NOI18N

        menuCadastro.setText("Cadastros");

        itemEstado.setText("Estado");
        itemEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEstadoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemEstado);

        itemCidade.setText("Cidade");
        itemCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCidadeActionPerformed(evt);
            }
        });
        menuCadastro.add(itemCidade);

        itemCliente.setText("Cliente");
        itemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(itemCliente);

        itemProduto.setText("Produto");
        itemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProdutoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemProduto);

        itemFormaPagamento.setText("Forma de Pagamento");
        itemFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFormaPagamentoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemFormaPagamento);

        jMenuBar1.add(menuCadastro);

        menuMovimentacao.setText("Movimentações");

        itemVenda.setText("Venda");
        itemVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVendaActionPerformed(evt);
            }
        });
        menuMovimentacao.add(itemVenda);

        jMenuBar1.add(menuMovimentacao);

        menuRelatorio.setText("Relatórios");

        itemClienteCadastrosCidades.setText("Cliente Cadastrados por Cidades");
        itemClienteCadastrosCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClienteCadastrosCidadesActionPerformed(evt);
            }
        });
        menuRelatorio.add(itemClienteCadastrosCidades);

        itemVendasRealizadasPeriodo.setText("Vendas Realizadas por Período");
        itemVendasRealizadasPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVendasRealizadasPeriodoActionPerformed(evt);
            }
        });
        menuRelatorio.add(itemVendasRealizadasPeriodo);

        jMenuBar1.add(menuRelatorio);

        menuSobre.setText("Sobre");

        Equipe.setText("Equipe");
        Equipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipeActionPerformed(evt);
            }
        });
        menuSobre.add(Equipe);

        jMenuBar1.add(menuSobre);
        menuSobre.getAccessibleContext().setAccessibleDescription("");

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEstadoActionPerformed
        new EstadoPesquisaTela().setVisible(true);
    }//GEN-LAST:event_itemEstadoActionPerformed

    private void itemCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCidadeActionPerformed
        new CidadePesquisaTela().setVisible(true);
    }//GEN-LAST:event_itemCidadeActionPerformed

    private void itemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClienteActionPerformed
        new ClientePesquisaTela().setVisible(true);
    }//GEN-LAST:event_itemClienteActionPerformed

    private void itemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProdutoActionPerformed
        new ProdutoPesquisaTela().setVisible(true);
    }//GEN-LAST:event_itemProdutoActionPerformed

    private void itemFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFormaPagamentoActionPerformed
        new FormaPagtoPesquisaTela().setVisible(true);
    }//GEN-LAST:event_itemFormaPagamentoActionPerformed

    private void itemVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVendaActionPerformed
        new TelaPesquisaVenda().setVisible(true);
    }//GEN-LAST:event_itemVendaActionPerformed

    private void EquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipeActionPerformed
       JOptionPane.showMessageDialog(null,"Antonio,Thais, Adriano, San, Felipe");
    }//GEN-LAST:event_EquipeActionPerformed

    private void itemClienteCadastrosCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClienteCadastrosCidadesActionPerformed
        new RelatorioClienteCidade().setVisible(true);
    }//GEN-LAST:event_itemClienteCadastrosCidadesActionPerformed

    private void itemVendasRealizadasPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVendasRealizadasPeriodoActionPerformed
        new RelatorioPorDataTela().setVisible(true);
    }//GEN-LAST:event_itemVendasRealizadasPeriodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Equipe;
    private javax.swing.JMenuItem itemCidade;
    private javax.swing.JMenuItem itemCliente;
    private javax.swing.JMenuItem itemClienteCadastrosCidades;
    private javax.swing.JMenuItem itemEstado;
    private javax.swing.JMenuItem itemFormaPagamento;
    private javax.swing.JMenuItem itemProduto;
    private javax.swing.JMenuItem itemVenda;
    private javax.swing.JMenuItem itemVendasRealizadasPeriodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuMovimentacao;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenu menuSobre;
    // End of variables declaration//GEN-END:variables
}
